# Generated by Django 4.0.4 on 2022-04-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('about', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_username', models.CharField(max_length=200, verbose_name='Ник в Telegram')),
                ('tg_id', models.PositiveIntegerField(unique=True, verbose_name='ID в Telegram')),
                ('steam_nickname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ник в Steam')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Поле "О себе"')),
                ('searchable', models.BooleanField(default=False, verbose_name='Разрешение на появление в поиске')),
                ('fav_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot_app.game', verbose_name='Любимая игра')),
            ],
        ),
    ]
